# Generated by Django 2.2.4 on 2019-09-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='default.jpg', upload_to='media/post_pics'),
        ),
    ]
